### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by viskin** [Telerik-Verified-Plugins/AppVersion#2]
Please update version from the upstream, as 0.1.7 API was significantly improved.

**Comment by EddyVerbruggen** [comment]
Thanks for letting us know. Just curious - is there any specific feature you'd like to use that's already in the upstream?

**Comment by viskin** [comment]
Yes, I have some generic logger. I want to retrieve getPackageName so I can use it in multiple different apps that access same backend.

**Comment by viskin** [comment]
And thank you for quick response :)
